services:
# Classes without dependencies
  Response:
    class:     Rapi\Response
  Campaign:
    class:     Rapi\Campiagn

# Classes with dependencies
  Actions:
    class:     Rapi\Call
    arguments: [@Container]
  Actions:
    class:     Rapi\Actions
    arguments: [@Response]
  Call:
    class:     Rapi\Call
    arguments: [@actions, @lists, @campaign, @Subscriber, @response, @subscribers, @templates]
  Common:
    class:     Rapi\Common
    arguments: [@PdoEx]
  Lists:
    class:     Rapi\Lists
    arguments: [@Common, @PdoEx, @Response]
  PdoEx:
    class:     Rapi\PdoEx
    arguments: [%pdoEx.hostname%, %pdoEx.username%, %pdoEx.pass%, %pdoEx.dbname%]
  Subscribers:
    class:     Rapi\Subscribers
    arguments: [@Common, @PdoEx, @Response]
  Templates:
    class:     Rapi\Templates
    arguments: [@Common]

# phpList 4 services
  CampaignEntity:
    class: phpList\helper\CampaignEntity
  MailingListEntity:
    class: phpList\helper\MailingListEntity
  SubscriberEntity:
    class: phpList\helper\SubscriberEntity
  TemplateEntity:
    class: phpList\helper\TemplateEntity
  TemplateImageEntity:
    class: phpList\helper\TemplateImageEntity
  Logger:
    class: phpList\helper\Logger
  Util:
    class: phpList\helper\Util
    arguments: [@Config, @Logger]
  EmailAddress:
    class:  phpList\EmailAddress
    arguments: [@Config, %emailaddress.address%]
  Password:
    class:  phpList\Password
    arguments: [@Config, %password.password%]
  Config:
    class: phpList\Config
    arguments: [%config.configfile%]
  Database:
    class:  phpList\helper\Database
    arguments: [@Config]
  Language:
    class: phpList\helper\Language
    arguments: [@Database, @Config]
  phpList:
    class: phpList\phpList
    arguments: [@Config, @Database, @Language, @Util]
  Campaign:
    class: phpList\Campaign
    arguments: [@Config, @Database, @MailingList, @Template]
  MailingList:
    class: phpList\MailingList
    arguments: [@Config, @Database]
  Subscriber:
    class: phpList\Subscriber
    arguments: [@Config, @Database]
  Template:
    class: phpList\Template
    arguments: [@Config, @Database, @TemplateImage]
  TemplateImage:
    class: phpList\TemplateImage
    arguments: [@Config, @Database]

# Define parameters, to be set in app logic
# NOTE: the classname.parameter syntax is just a Symfony convention; parameter
# names are handles as single simple strings
parameters:
  pdoEx.hostname: hostname
  pdoEx.username: username
  pdoEx.pass: pass
  pdoEx.dbname: dbname

# phpList 4 parameters
  config.configfile: config_file
  emailaddress.address: email_address
  password.password: password
